### ISSUE TITLE
Paint - gene with maximum expression change isn't colored

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/app-ui#320]
The gene with maximum magnitude fold change is used as the bounds of the color map but it doesn't get colored in the graph.
See example:

![screenshot at dec 09 18-20-18](https://user-images.githubusercontent.com/4706307/33800450-c3999c3c-dd0d-11e7-86fa-e947aa2dc6ff.png)

**Comment by d2fong** [comment]
Can you post the cy session file

**Comment by jvwong** [comment]
[tep_enrichmentmap.cys.zip](https://github.com/PathwayCommons/app-ui/files/1545778/tep_enrichmentmap.cys.zip)

**Comment by jvwong** [comment]
Possibly related: for the "Ras Pathway" the painter is ignoring the max altogether (e.g. MAPK9). This happens on two different cys files.

![ras_pathway](https://user-images.githubusercontent.com/4706307/33807066-4ab4b4c2-dd9f-11e7-8ac5-d7e2fc54ce16.png)

**Comment by d2fong** [comment]
The problem with the ras pathway example is that MAPK9 isnt found in the network.

I guess thats another hidden issue, the data in the table should be greyed out if it is not found in the network.

**Comment by jvwong** [comment]
i would have assumed (until now) that the expression data is a subset of the geneset.

**Comment by d2fong** [comment]
Its not from my experience.  Anyways I pushed a fix to the demo branch can you see if it works for the p21 pathway?

**Comment by d2fong** [comment]
At least the labels will not exactly be the same, for example there is no node with exactly MAPK9 but there is MAPKAP MAP3K7CL

**Comment by jvwong** [comment]
Methinks this boils down to a gene synonym issue:

- Looked at [MAPK9 synonyms in Entrez Gene](https://www.ncbi.nlm.nih.gov/gene/5601) which includes a bunch of JNKx references

- GMT file and SIF coming out of the [Search app](http://localhost:3000/view?uri=http%3A%2F%2Fidentifiers.org%2Fpanther.pathway%2FP04393) have MAPK9; but no SBGN representation of this label, but do have a 'JNK' entity that seems to participate in all the stated reactions

- Original [Panther pathways](http://pantherdb.org/pathway/pathwayList.do?searchType=basic&fieldName=all&organism=all&listType=8&fieldValue=ras) has 'Ras pathway' with no mention of MAPK9 but again, JNK that seems to be involved in the related reactions.

There's a bunch of other synonym issues, and sometimes the individual genes are collapsed into at single entity in the view (e.g. PAK vs PAK1 PAK2 PAK3).

jw

**Comment by jvwong** [comment]
FYI from the bioPAX

```xml
...
<bp:ProteinReference rdf:ID="ProteinReference_62367ea39ff44b5cf2c4af19e2f38838">
 <bp:standardName rdf:datatype = "http://www.w3.org/2001/XMLSchema#string">Jun kinase n-terminal kinase</bp:standardName>
 <bp:xref rdf:resource="#UnificationXref_panther_pathway_component_P04572" />
 <bp:memberEntityReference rdf:resource="http://identifiers.org/uniprot/P45984" />
 <bp:memberEntityReference rdf:resource="http://identifiers.org/uniprot/P45983" />
 <bp:memberEntityReference rdf:resource="http://identifiers.org/uniprot/P53779" />
 <bp:displayName rdf:datatype = "http://www.w3.org/2001/XMLSchema#string">JNK</bp:displayName>
 <bp:comment rdf:datatype = "http://www.w3.org/2001/XMLSchema#string">ENTITY_REFERENCE_ID_DESC=Ras Pathway.PROTEIN.GENERIC.JNK</bp:comment>
 <bp:comment rdf:datatype = "http://www.w3.org/2001/XMLSchema#string">ENTITY_REFERENCE_NOTES= Long Name: Jun kinase n-terminal kinase Synonym: JNK,SAPK,stress activated protein kinase Accession: P04572 </bp:comment>
 <bp:comment rdf:datatype = "http://www.w3.org/2001/XMLSchema#string">ENTITY_REFERENCE_PROTEIN_TYPE=GENERIC</bp:comment>
 <bp:comment rdf:datatype = "http://www.w3.org/2001/XMLSchema#string">REPLACED http://www.pantherdb.org/pathways/biopax/P04393#_JNK_PROTEIN</bp:comment>
</bp:ProteinReference>
...

<bp:ProteinReference rdf:about="http://identifiers.org/uniprot/P45984">
 <bp:entityFeature rdf:resource="#ModificationFeature_586e504f8d66ec6a2e781ff7cfbb2321" />
 <bp:entityFeature rdf:resource="#ModificationFeature_465ab9bc807d1568b905867f7280d7d9" />
 <bp:entityFeature rdf:resource="#ModificationFeature_5d1dd246f225aa6a1453b48ad695af02" />
 <bp:entityFeature rdf:resource="#ModificationFeature_3e507a999d704211debd5a0f7661d8d1" />
 <bp:standardName rdf:datatype = "http://www.w3.org/2001/XMLSchema#string">Mitogen-activated protein kinase 9</bp:standardName>
 <bp:xref rdf:resource="#UnificationXref_uniprot_knowledgebase_P45984" />
 <bp:xref rdf:resource="#RelationshipXref_hgnc_symbol_MAPK9_identity" />
 <bp:organism rdf:resource="http://identifiers.org/taxonomy/9606" />
 <bp:displayName rdf:datatype = "http://www.w3.org/2001/XMLSchema#string">MK09_HUMAN</bp:displayName>
 <bp:name rdf:datatype = "http://www.w3.org/2001/XMLSchema#string">PRKM9</bp:name>
 <bp:name rdf:datatype = "http://www.w3.org/2001/XMLSchema#string">SAPK1a</bp:name>
 <bp:name rdf:datatype = "http://www.w3.org/2001/XMLSchema#string">2.7.11.24</bp:name>
 <bp:name rdf:datatype = "http://www.w3.org/2001/XMLSchema#string">Stress-activated protein kinase JNK2</bp:name>
 <bp:name rdf:datatype = "http://www.w3.org/2001/XMLSchema#string">Stress-activated protein kinase 1a</bp:name>
 <bp:name rdf:datatype = "http://www.w3.org/2001/XMLSchema#string">MAPK 9</bp:name>
 <bp:name rdf:datatype = "http://www.w3.org/2001/XMLSchema#string">MAP kinase 9</bp:name>
 <bp:name rdf:datatype = "http://www.w3.org/2001/XMLSchema#string">c-Jun N-terminal kinase 2</bp:name>
 <bp:name rdf:datatype = "http://www.w3.org/2001/XMLSchema#string">JNK2</bp:name>
 <bp:name rdf:datatype = "http://www.w3.org/2001/XMLSchema#string">MAPK9</bp:name>
 <bp:name rdf:datatype = "http://www.w3.org/2001/XMLSchema#string">SAPK1A</bp:name>
 <bp:name rdf:datatype = "http://www.w3.org/2001/XMLSchema#string">JNK-55</bp:name>
 <bp:comment rdf:datatype = "http://www.w3.org/2001/XMLSchema#string">REPLACED http://www.phosphosite.org/phosphosite.owl#po_3552</bp:comment>
 <bp:comment rdf:datatype = "http://www.w3.org/2001/XMLSchema#string">REPLACED http://pathwaycommons.org/pc2/ProteinReference_uniprotkb_P45984_identity</bp:comment>
 <bp:comment rdf:datatype = "http://www.w3.org/2001/XMLSchema#string">REPLACED http://pathwaycommons.org/pc2/ProteinReference_dip_DIP-281N_identity</bp:comment>
 <bp:comment rdf:datatype = "http://www.w3.org/2001/XMLSchema#string">REPLACED ProteinRef_MAPK9__10090</bp:comment>
 <bp:comment rdf:datatype = "http://www.w3.org/2001/XMLSchema#string">REPLACED http://identifiers.org/uniprot/J3KNK1</bp:comment>
 <bp:comment rdf:datatype = "http://www.w3.org/2001/XMLSchema#string">REPLACED http://mirtarbase.mbc.nctu.edu.tw/#ref_5601</bp:comment>
 <bp:comment rdf:datatype = "http://www.w3.org/2001/XMLSchema#string">FUNCTION: Serine/threonine-protein kinase involved in variousprocesses such as cell proliferation, differentiation, migration,transformation and programmed cell death. Extracellular stimulisuch as proinflammatory cytokines or physical stress stimulate thestress-activated protein kinase/c-Jun N-terminal kinase (SAP/JNK)signaling pathway. In this cascade, two dual specificity kinasesMAP2K4/MKK4 and MAP2K7/MKK7 phosphorylate and activate MAPK9/JNK2.In turn, MAPK9/JNK2 phosphorylates a number of transcriptionfactors, primarily components of AP-1 such as JUN and ATF2 andthus regulates AP-1 transcriptional activity. In response tooxidative or ribotoxic stresses, inhibits rRNA synthesis byphosphorylating and inactivating the RNA polymerase 1-specifictranscription initiation factor RRN3. Promotes stressed cellapoptosis by phosphorylating key regulatory factors including TP53and YAP1. In T-cells, MAPK8 and MAPK9 are required for polarizeddifferentiation of T-helper cells into Th1 cells. Upon T-cellreceptor (TCR) stimulation, is activated by CARMA1, BCL10, MAP2K7and MAP3K7/TAK1 to regulate JUN protein levels. Plays an importantrole in the osmotic stress-induced epithelial tight-junctionsdisruption. When activated, promotes beta-catenin/CTNNB1degradation and inhibits the canonical Wnt signaling pathway.Participates also in neurite growth in spiral ganglion neurons.Phosphorylates the CLOCK-ARNTL/BMAL1 heterodimer and plays a rolein the regulation of the circadian clock (PubMed:22441692).{ECO:0000269|PubMed:22441692}.FUNCTION: MAPK9 isoforms display different binding patterns:alpha-1 and alpha-2 preferentially bind to JUN, whereas beta-1 andbeta-2 bind to ATF2. However, there is no correlation betweenbinding and phosphorylation, which is achieved at about the sameefficiency by all isoforms. JUNB is not a substrate for JNK2alpha-2, and JUND binds only weakly to it.CATALYTIC ACTIVITY: ATP + a protein = ADP + a phosphoprotein.COFACTOR:Name=Mg(2+); Xref=ChEBI:CHEBI:18420;Evidence={ECO:0000269|PubMed:11062067};ENZYME REGULATION: Activated by threonine and tyrosinephosphorylation by either of two dual specificity kinases, MAP2K4and MAP2K7. MAP2K4 shows a strong preference for Tyr-185 whileMAP2K7 phosphorylates Tyr-183 preferentially. Inhibited by dualspecificity phosphatases, such as DUSP1.SUBUNIT: Interacts with MECOM (By similarity). Interacts withDCLK2 (By similarity). Binds to at least four scaffoldingproteins, MAPK8IP1/JIP-1, MAPK8IP2/JIP-2, MAPK8IP3/JIP-3/JSAP1 andSPAG9/MAPK8IP4/JIP-4. These proteins also bind other components ofthe JNK signaling pathway (By similarity). Interacts with NFATC4(PubMed:17875713). Interacts with ATF7; the interaction does notphosphorylate ATF7 but acts as a docking site for ATF7-associatedpartners such as JUN (PubMed:10376527). Interacts with BCL10(PubMed:17189706). Interacts with CTNNB1 and GSK3B(PubMed:19675674). Interacts with MAPKBP1 (PubMed:28089251).{ECO:0000250|UniProtKB:P49186, ECO:0000250|UniProtKB:Q9WTU6,ECO:0000269|PubMed:10376527, ECO:0000269|PubMed:17189706,ECO:0000269|PubMed:17875713, ECO:0000269|PubMed:19675674,ECO:0000269|PubMed:28089251}.SUBCELLULAR LOCATION: Cytoplasm {ECO:0000269|PubMed:19675674}.Nucleus {ECO:0000269|PubMed:19675674}.ALTERNATIVE PRODUCTS:Event=Alternative splicing; Named isoforms=5;Name=Alpha-2;IsoId=P45984-1; Sequence=Displayed;Name=Alpha-1;IsoId=P45984-2; Sequence=VSP_004835;Name=Beta-1;IsoId=P45984-3; Sequence=VSP_004834, VSP_004835;Name=Beta-2;IsoId=P45984-4; Sequence=VSP_004834;Name=5;IsoId=P45984-5; Sequence=VSP_041908, VSP_041909;DOMAIN: The TXY motif contains the threonine and tyrosine residueswhose phosphorylation activates the MAP kinases.PTM: Dually phosphorylated on Thr-183 and Tyr-185 by MAP2K7 andMAP2K4, which activates the enzyme. Autophosphorylated in vitro.{ECO:0000269|PubMed:11062067}.SIMILARITY: Belongs to the protein kinase superfamily. CMGCSer/Thr protein kinase family. MAP kinase subfamily.{ECO:0000305}.WEB RESOURCE: Name=Atlas of Genetics and Cytogenetics in Oncologyand Haematology;URL=&quot;http://atlasgeneticsoncology.org/Genes/JNK2ID426.html&quot;;WEB RESOURCE: Name=NIEHS-SNPs;URL=&quot;http://egp.gs.washington.edu/data/mapk9/&quot;; COPYRIGHT: UniProt Consortium (www.uniprot.org). Distributed under the Creative Commons Attribution-NoDerivs License.</bp:comment>
 <bp:comment rdf:datatype = "http://www.w3.org/2001/XMLSchema#string">REPLACED ProteinRef_MAPK9__9606</bp:comment>
 <bp:comment rdf:datatype = "http://www.w3.org/2001/XMLSchema#string">REPLACED http://identifiers.org/uniprot.isoform/P45984-1</bp:comment>
 <bp:comment rdf:datatype = "http://www.w3.org/2001/XMLSchema#string">REPLACED http://pathwaycommons.org/pc2/ProteinReference_HPRD_04206_identity</bp:comment>
 <bp:comment rdf:datatype = "http://www.w3.org/2001/XMLSchema#string">REPLACED ProteinRef_MAPK9__40674</bp:comment>
 <bp:comment rdf:datatype = "http://www.w3.org/2001/XMLSchema#string">REPLACED http://www.phosphosite.org/phosphosite.owl#po_1234</bp:comment>
 <bp:comment rdf:datatype = "http://www.w3.org/2001/XMLSchema#string">REPLACED http://www.ctdbase.org/#ref_protein_gene_5601</bp:comment>
 <bp:comment rdf:datatype = "http://www.w3.org/2001/XMLSchema#string">REPLACED http://identifiers.org/ncbigene/5601</bp:comment>
 <bp:comment rdf:datatype = "http://www.w3.org/2001/XMLSchema#string">REPLACED http://identifiers.org/refseq/NP_002743</bp:comment>
 <bp:comment rdf:datatype = "http://www.w3.org/2001/XMLSchema#string">REPLACED http://pathwaycommons.org/pc2/ProteinReference_dip_DIP-270N_identity</bp:comment>
 <bp:comment rdf:datatype = "http://www.w3.org/2001/XMLSchema#string">MK09_HUMAN Reviewed; 424 AA.</bp:comment>
 <bp:comment rdf:datatype = "http://www.w3.org/2001/XMLSchema#string">REPLACED http://identifiers.org/refseq/NP_620709</bp:comment>
 <bp:comment rdf:datatype = "http://www.w3.org/2001/XMLSchema#string">REPLACED http://identifiers.org/refseq/NP_620708</bp:comment>
 <bp:comment rdf:datatype = "http://www.w3.org/2001/XMLSchema#string">REPLACED http://identifiers.org/refseq/NP_620707</bp:comment>
</bp:ProteinReference>

```

**Comment by d2fong** [comment]
Also your demo branch has deviated from the dev branch there are a few differences that are fixed in the dev branch such as only having two decimal places, etc.

**Comment by jvwong** [comment]
THis 18fc20f15d0513f93b89c0585fc02fa2b8a26dad commit is still showing the decimals.

**Comment by jvwong** [comment]
Nevermind I was thinking the demo branch.

**Comment by d2fong** [comment]
Cherry-picked the commits over, you should have all the changes from the dev branch now.

**Comment by jvwong** [comment]
Looks good. I think we need @IgorRodchenkov in on the discussion of how to reconcile GMT representation with SBGN representation. This ras pathway is an extreme example whereby only one gene maps!

**Comment by d2fong** [comment]
Thats a story for another time.
